#!/bin/zsh

if [[ $1 -eq "8" ]] ; then
    export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
    `java -version`
elif [[ $1 -eq "11" ]] ; then
    export JAVA_HOME=`/usr/libexec/java_home -v 11`
    `java -version`
else
    echo "Unsupported Java version specified: $1"
fi
